"""Constants for Meteo UA integration."""

DOMAIN = "meteo_ua"

CONF_CITY_ID = "city_id"
CONF_CITY_SLUG = "city_slug"
CONF_CITY_NAME = "city_name"
CONF_STATION_ID = "station_id"

DEFAULT_CITY_ID = "33"
DEFAULT_CITY_SLUG = "vyshgorod"
DEFAULT_CITY_NAME = "Вишгород"
DEFAULT_STATION_ID = "33345"

UPDATE_INTERVAL_CURRENT = 1800   # 30 min
UPDATE_INTERVAL_FORECAST = 7200  # 2 hours

INFORMER_URL = "https://www.meteo.gov.ua/ua/informer/{station}.js"
MONTHLY_URL = "https://meteo.ua/{city_id}/{city_slug}/month"

# meteo.ua icon name -> HA weather condition
ICON_TO_HA_CONDITION = {
    "clear-sky": "sunny",
    "few-clouds-11-25": "partlycloudy",
    "scattered-clouds-25-50": "partlycloudy",
    "broken-clouds-51-84": "cloudy",
    "overcast-clouds-85-100": "cloudy",
    "light-rain": "rainy",
    "moderate-rain": "rainy",
    "heavy-rain": "pouring",
    "thunderstorm": "lightning",
    "thunderstorm-with-rain": "lightning-rainy",
    "thunderstorm-with-heavy-rain": "lightning-rainy",
    "light-snow": "snowy",
    "moderate-snow": "snowy",
    "heavy-snow": "snowy",
    "rain-and-snow": "snowy-rainy",
    "sleet": "snowy-rainy",
    "fog": "fog",
    "mist": "fog",
    "haze": "fog",
}

# Ukrainian weather text keyword -> HA condition
CONDITION_TEXT_MAP = {
    "гроз": "lightning-rainy",
    "злив": "pouring",
    "дощ": "rainy",
    "снігопад": "snowy",
    "сніг": "snowy",
    "туман": "fog",
    "ясно": "sunny",
    "малохмарно": "sunny",
    "мінлив": "partlycloudy",
    "проясн": "partlycloudy",
    "хмарно": "cloudy",
}

WIND_DIR_DEGREES = {
    "N": 0, "NNE": 22, "NE": 45, "ENE": 67,
    "E": 90, "ESE": 112, "SE": 135, "SSE": 157,
    "S": 180, "SSW": 202, "SW": 225, "WSW": 247,
    "W": 270, "WNW": 292, "NW": 315, "NNW": 337,
}

CITIES = [
    # ── Київська область ──────────────────────────────────────────────
    {"id": "34",  "slug": "kiev",                     "name": "Київ",                  "station": "33345"},
    {"id": "33",  "slug": "vyshgorod",                "name": "Вишгород",              "station": "33345"},
    {"id": "589", "slug": "brovary",                  "name": "Бровари",               "station": "33345"},
    {"id": "590", "slug": "bucha",                    "name": "Буча",                  "station": "33345"},
    {"id": "592", "slug": "irpen",                    "name": "Ірпінь",                "station": "33345"},
    {"id": "35",  "slug": "borispol",                 "name": "Бориспіль",             "station": "33345"},
    {"id": "52",  "slug": "belaya-tserkov",           "name": "Біла Церква",           "station": "33345"},
    {"id": "591", "slug": "vasilkov",                 "name": "Василків",              "station": "33345"},
    {"id": "32",  "slug": "fastov",                   "name": "Фастів",                "station": "33345"},
    {"id": "601", "slug": "obukhov",                  "name": "Обухів",                "station": "33345"},
    {"id": "595", "slug": "slavutich",                "name": "Славутич",              "station": "33345"},
    {"id": "596", "slug": "boguslav",                 "name": "Богуслав",              "station": "33345"},
    {"id": "37",  "slug": "yagotin",                  "name": "Яготин",                "station": "33345"},
    {"id": "36",  "slug": "baryshevka",               "name": "Баришівка",             "station": "33345"},
    {"id": "53",  "slug": "mironovka",                "name": "Миронівка",             "station": "33345"},
    {"id": "600", "slug": "kagarlyk",                 "name": "Кагарлик",              "station": "33345"},
    {"id": "602", "slug": "skvira",                   "name": "Сквира",                "station": "33345"},
    # ── Чернігівська область ──────────────────────────────────────────
    {"id": "6",   "slug": "chernigov",                "name": "Чернігів",              "station": "33135"},
    {"id": "20",  "slug": "nejin",                    "name": "Ніжин",                 "station": "33135"},
    {"id": "38",  "slug": "priluki",                  "name": "Прилуки",               "station": "33135"},
    {"id": "1255","slug": "baturin",                  "name": "Батурин",               "station": "33135"},
    {"id": "1258","slug": "gorodnya",                 "name": "Городня",               "station": "33135"},
    {"id": "1260","slug": "koryukovka",               "name": "Корюківка",             "station": "33135"},
    {"id": "1261","slug": "mena",                     "name": "Мена",                  "station": "33135"},
    {"id": "1273","slug": "kozelets",                 "name": "Козелець",              "station": "33135"},
    {"id": "1263","slug": "nosovka",                  "name": "Носівка",               "station": "33135"},
    # ── Сумська область ───────────────────────────────────────────────
    {"id": "23",  "slug": "sumyi",                    "name": "Суми",                  "station": "33275"},
    {"id": "1046","slug": "shostka",                  "name": "Шостка",                "station": "33275"},
    {"id": "1045","slug": "akhtyrka",                 "name": "Ахтирка",               "station": "33275"},
    {"id": "21",  "slug": "konotop",                  "name": "Конотоп",               "station": "33275"},
    {"id": "22",  "slug": "romny",                    "name": "Ромни",                 "station": "33275"},
    {"id": "41",  "slug": "lebedin",                  "name": "Лебедин",               "station": "33275"},
    {"id": "9",   "slug": "glukhov",                  "name": "Глухів",                "station": "33275"},
    {"id": "1049","slug": "krolevets",                "name": "Кролевець",             "station": "33275"},
    {"id": "1052","slug": "trostyanets",              "name": "Тростянець",            "station": "33275"},
    {"id": "1050","slug": "putivl",                   "name": "Путивль",               "station": "33275"},
    # ── Житомирська область ───────────────────────────────────────────
    {"id": "31",  "slug": "jitomir",                  "name": "Житомир",               "station": "33301"},
    {"id": "16",  "slug": "korosten",                 "name": "Коростень",             "station": "33301"},
    {"id": "464", "slug": "berdichev",                "name": "Бердичів",              "station": "33301"},
    {"id": "15",  "slug": "ovruch",                   "name": "Овруч",                 "station": "33301"},
    {"id": "465", "slug": "malin",                    "name": "Малин",                 "station": "33301"},
    {"id": "468", "slug": "korostyishev",             "name": "Коростишів",            "station": "33301"},
    {"id": "469", "slug": "radomyishl",               "name": "Радомишль",             "station": "33301"},
    {"id": "14",  "slug": "olevsk",                   "name": "Олевськ",               "station": "33301"},
    # ── Рівненська область ────────────────────────────────────────────
    {"id": "28",  "slug": "rovno",                    "name": "Рівне",                 "station": "33181"},
    {"id": "25",  "slug": "dubno",                    "name": "Дубно",                 "station": "33181"},
    {"id": "1021","slug": "kuznetsovsk",              "name": "Вараш",                 "station": "33181"},
    {"id": "5",   "slug": "sarny",                    "name": "Сарни",                 "station": "33181"},
    {"id": "1025","slug": "zdolbunov",                "name": "Здолбунів",             "station": "33181"},
    {"id": "1022","slug": "ostrog",                   "name": "Острог",                "station": "33181"},
    {"id": "1027","slug": "kostopol",                 "name": "Костопіль",             "station": "33181"},
    {"id": "1024","slug": "dubrovitsa",               "name": "Дубровиця",             "station": "33181"},
    # ── Волинська область ─────────────────────────────────────────────
    {"id": "13",  "slug": "lutsk",                    "name": "Луцьк",                 "station": "33187"},
    {"id": "10",  "slug": "kovel",                    "name": "Ковель",                "station": "33187"},
    {"id": "225", "slug": "novovolynsk",              "name": "Нововолинськ",          "station": "33187"},
    {"id": "244", "slug": "kivertsyi",                "name": "Ківерці",               "station": "33187"},
    {"id": "246", "slug": "rozhishche",               "name": "Рожище",                "station": "33187"},
    {"id": "245", "slug": "lyuboml",                  "name": "Любомль",               "station": "33187"},
    {"id": "12",  "slug": "manevichi",                "name": "Маневичі",              "station": "33187"},
    # ── Львівська область ─────────────────────────────────────────────
    {"id": "44",  "slug": "lvov",                     "name": "Львів",                 "station": "33393"},
    {"id": "45",  "slug": "drogobyich",               "name": "Дрогобич",              "station": "33393"},
    {"id": "60",  "slug": "stryiy",                   "name": "Стрий",                 "station": "33393"},
    {"id": "864", "slug": "borislav",                 "name": "Борислав",              "station": "33393"},
    {"id": "867", "slug": "sambor",                   "name": "Самбір",                "station": "33393"},
    {"id": "868", "slug": "chervonograd",             "name": "Червоноград",           "station": "33393"},
    {"id": "866", "slug": "novyy-rozdol",             "name": "Новий Розділ",          "station": "33393"},
    {"id": "43",  "slug": "yavorov",                  "name": "Яворів",                "station": "33393"},
    {"id": "26",  "slug": "brody",                    "name": "Броди",                 "station": "33393"},
    {"id": "889", "slug": "sokal",                    "name": "Сокаль",                "station": "33393"},
    {"id": "59",  "slug": "turka",                    "name": "Турка",                 "station": "33393"},
    {"id": "63",  "slug": "slavskoe",                 "name": "Славське",              "station": "33393"},
    {"id": "865", "slug": "morshin",                  "name": "Моршин",                "station": "33393"},
    # ── Тернопільська область ─────────────────────────────────────────
    {"id": "47",  "slug": "ternopol",                 "name": "Тернопіль",             "station": "33509"},
    {"id": "68",  "slug": "chortkov",                 "name": "Чортків",               "station": "33509"},
    {"id": "46",  "slug": "berezhany",                "name": "Бережани",              "station": "33509"},
    {"id": "27",  "slug": "kremenets",                "name": "Кременець",             "station": "33509"},
    {"id": "1073","slug": "borshchev",                "name": "Борщів",                "station": "33509"},
    {"id": "1074","slug": "buchach",                  "name": "Бучач",                 "station": "33509"},
    {"id": "1084","slug": "terebovlya",               "name": "Теребовля",             "station": "33509"},
    {"id": "1076","slug": "zbarazh",                  "name": "Збараж",                "station": "33509"},
    # ── Хмельницька область ───────────────────────────────────────────
    {"id": "49",  "slug": "khmelnitskiy",             "name": "Хмельницький",          "station": "33506"},
    {"id": "69",  "slug": "kamenets-podolskiy",       "name": "Кам'янець-Подільський", "station": "33506"},
    {"id": "30",  "slug": "shepetovka",               "name": "Шепетівка",             "station": "33506"},
    {"id": "1203","slug": "neteshin",                 "name": "Нетешин",               "station": "33506"},
    {"id": "1204","slug": "slavuta",                  "name": "Славута",               "station": "33506"},
    {"id": "1220","slug": "dunaevtsyi",               "name": "Дунаївці",              "station": "33506"},
    # ── Івано-Франківська область ─────────────────────────────────────
    {"id": "67",  "slug": "ivano-frankovsk",          "name": "Івано-Франківськ",      "station": "33415"},
    {"id": "89",  "slug": "kolomyiya",                "name": "Коломия",               "station": "33415"},
    {"id": "557", "slug": "kalush",                   "name": "Калуш",                 "station": "33415"},
    {"id": "66",  "slug": "dolina",                   "name": "Долина",                "station": "33415"},
    {"id": "561", "slug": "nadvirna",                 "name": "Надвірна",              "station": "33415"},
    {"id": "86",  "slug": "yaremcha",                 "name": "Яремче",                "station": "33415"},
    {"id": "562", "slug": "rogatin",                  "name": "Рогатин",               "station": "33415"},
    {"id": "563", "slug": "snyatyn",                  "name": "Снятин",                "station": "33415"},
    {"id": "1311","slug": "bukovel",                  "name": "Буковель",              "station": "33415"},
    {"id": "1349","slug": "verkhovina",               "name": "Верховина",             "station": "33415"},
    # ── Закарпатська область ──────────────────────────────────────────
    {"id": "83",  "slug": "uzhgorod",                 "name": "Ужгород",               "station": "33631"},
    {"id": "84",  "slug": "beregovo",                 "name": "Берегово",              "station": "33631"},
    {"id": "85",  "slug": "hust",                     "name": "Хуст",                  "station": "33631"},
    {"id": "88",  "slug": "rahov",                    "name": "Рахів",                 "station": "33631"},
    {"id": "1347","slug": "svalyava",                 "name": "Свалява",               "station": "33631"},
    {"id": "512", "slug": "vinogradov",               "name": "Виноградів",            "station": "33631"},
    {"id": "511", "slug": "chop",                     "name": "Чоп",                   "station": "33631"},
    {"id": "513", "slug": "irshava",                  "name": "Іршава",                "station": "33631"},
    # ── Чернівецька область ───────────────────────────────────────────
    {"id": "91",  "slug": "chernovtsyi",              "name": "Чернівці",              "station": "33466"},
    {"id": "92",  "slug": "novodnestrovsk",           "name": "Новодністровськ",        "station": "33466"},
    {"id": "1294","slug": "vizhnitsa",                "name": "Вижниця",               "station": "33466"},
    {"id": "1297","slug": "kitsman",                  "name": "Кіцмань",               "station": "33466"},
    {"id": "1299","slug": "sokiryany",                "name": "Сокиряни",              "station": "33466"},
    {"id": "1301","slug": "hotin",                    "name": "Хотин",                 "station": "33466"},
    {"id": "1300","slug": "storozhinets",             "name": "Сторожинець",           "station": "33466"},
    # ── Вінницька область ─────────────────────────────────────────────
    {"id": "71",  "slug": "vinnitsa",                 "name": "Вінниця",               "station": "33562"},
    {"id": "72",  "slug": "zhmerinka",                "name": "Жмеринка",              "station": "33562"},
    {"id": "73",  "slug": "gaysin",                   "name": "Гайсин",                "station": "33562"},
    {"id": "186", "slug": "kazatin",                  "name": "Козятин",               "station": "33562"},
    {"id": "187", "slug": "ladyzhin",                 "name": "Ладижин",               "station": "33562"},
    {"id": "188", "slug": "bar",                      "name": "Бар",                   "station": "33562"},
    {"id": "194", "slug": "nemirov",                  "name": "Немирів",               "station": "33562"},
    {"id": "196", "slug": "tulchin",                  "name": "Тульчин",               "station": "33562"},
    {"id": "197", "slug": "shargorod",                "name": "Шаргород",              "station": "33562"},
    {"id": "76",  "slug": "uman",                     "name": "Умань",                 "station": "33721"},
    # ── Черкаська область ─────────────────────────────────────────────
    {"id": "56",  "slug": "cherkassyi",               "name": "Черкаси",               "station": "33721"},
    {"id": "54",  "slug": "kanev",                    "name": "Канів",                 "station": "33721"},
    {"id": "55",  "slug": "zolotonosha",              "name": "Золотоноша",            "station": "33721"},
    {"id": "77",  "slug": "smela",                    "name": "Сміла",                 "station": "33721"},
    {"id": "75",  "slug": "zvenigorodka",             "name": "Звенигородка",          "station": "33721"},
    {"id": "79",  "slug": "chigirin",                 "name": "Чигирин",               "station": "33721"},
    {"id": "74",  "slug": "zhashkov",                 "name": "Жашків",                "station": "33721"},
    {"id": "1241","slug": "shpola",                   "name": "Шпола",                 "station": "33721"},
    # ── Кіровоградська область ────────────────────────────────────────
    {"id": "97",  "slug": "kropivnitskiy-kirovograd", "name": "Кропивницький",         "station": "33711"},
    {"id": "637", "slug": "aleksandriya",             "name": "Олександрія",           "station": "33711"},
    {"id": "81",  "slug": "svetlovodsk",              "name": "Світловодськ",          "station": "33711"},
    {"id": "80",  "slug": "znamenka",                 "name": "Знам'янка",             "station": "33711"},
    {"id": "78",  "slug": "novomirgorod",             "name": "Новомиргород",          "station": "33711"},
    {"id": "94",  "slug": "gayvoron",                 "name": "Гайворон",              "station": "33711"},
    {"id": "99",  "slug": "dolinskaya",               "name": "Долинська",             "station": "33711"},
    # ── Полтавська область ────────────────────────────────────────────
    {"id": "58",  "slug": "poltava",                  "name": "Полтава",               "station": "33978"},
    {"id": "990", "slug": "kremenchug",               "name": "Кременчук",             "station": "33946"},
    {"id": "991", "slug": "mirgorod",                 "name": "Миргород",              "station": "33978"},
    {"id": "989", "slug": "komsomolsk",               "name": "Горішні Плавні",        "station": "33978"},
    {"id": "40",  "slug": "lubny",                    "name": "Лубни",                 "station": "33978"},
    {"id": "39",  "slug": "gadyach",                  "name": "Гадяч",                 "station": "33978"},
    {"id": "997", "slug": "piryatin",                 "name": "Пирятин",               "station": "33978"},
    {"id": "82",  "slug": "kobelyaki",                "name": "Кобеляки",              "station": "33978"},
    {"id": "993", "slug": "grebenka",                 "name": "Гребінка",              "station": "33978"},
    # ── Дніпропетровська область ──────────────────────────────────────
    {"id": "164", "slug": "dnepr-dnepropetrovsk",     "name": "Дніпро",                "station": "34504"},
    {"id": "105", "slug": "krivoy-rog",               "name": "Кривий Ріг",            "station": "34401"},
    {"id": "106", "slug": "nikopol",                  "name": "Нікополь",              "station": "34504"},
    {"id": "163", "slug": "pavlograd",                "name": "Павлоград",             "station": "34504"},
    {"id": "255", "slug": "jeltyie-vodyi",            "name": "Жовті Води",            "station": "34504"},
    {"id": "257", "slug": "novomoskovsk",             "name": "Новомосковськ",         "station": "34504"},
    {"id": "253", "slug": "volnogorsk",               "name": "Вільногірськ",          "station": "34504"},
    {"id": "267", "slug": "pyatihatki",               "name": "П'ятихатки",            "station": "34504"},
    {"id": "256", "slug": "marganets",                "name": "Марганець",             "station": "34504"},
    # ── Харківська область ────────────────────────────────────────────
    {"id": "150", "slug": "harkov",                   "name": "Харків",                "station": "34300"},
    {"id": "1104","slug": "lyubotin",                 "name": "Люботин",               "station": "34300"},
    {"id": "1106","slug": "chuguev",                  "name": "Чугуїв",                "station": "34300"},
    {"id": "1107","slug": "balakleya",                "name": "Балаклія",              "station": "34300"},
    {"id": "159", "slug": "lozovaya",                 "name": "Лозова",                "station": "34300"},
    {"id": "160", "slug": "izyum",                    "name": "Ізюм",                  "station": "34300"},
    {"id": "1112","slug": "zmiev",                    "name": "Зміїв",                 "station": "34300"},
    {"id": "1113","slug": "merefa",                   "name": "Мерефа",                "station": "34300"},
    {"id": "149", "slug": "zolochev",                 "name": "Золочів",               "station": "34300"},
    {"id": "151", "slug": "bogoduhov",                "name": "Богодухів",             "station": "34300"},
    {"id": "157", "slug": "krasnograd",               "name": "Красноград",            "station": "34300"},
    {"id": "1111","slug": "dergachi",                 "name": "Дергачі",               "station": "34300"},
    # ── Донецька область ──────────────────────────────────────────────
    {"id": "313", "slug": "kramatorsk",               "name": "Краматорськ",           "station": "34519"},
    {"id": "340", "slug": "svyatogorsk",              "name": "Святогірськ",           "station": "34519"},
    {"id": "341", "slug": "seversk",                  "name": "Сєвєрськ",              "station": "34519"},
    {"id": "306", "slug": "dobropole",                "name": "Добропілля",            "station": "34519"},
    {"id": "308", "slug": "drujkovka",                "name": "Дружківка",             "station": "34519"},
    {"id": "333", "slug": "kurakhovo",                "name": "Курахове",              "station": "34519"},
    {"id": "176", "slug": "volnovaha",                "name": "Волноваха",             "station": "34519"},
    # ── Луганська область ─────────────────────────────────────────────
    {"id": "170", "slug": "lugansk",                  "name": "Луганськ",              "station": "34504"},
    {"id": "735", "slug": "severodonetsk",            "name": "Сєвєродонецьк",         "station": "34504"},
    {"id": "730", "slug": "lisichansk",               "name": "Лисичанськ",            "station": "34504"},
    {"id": "756", "slug": "starobelsk",               "name": "Старобільськ",          "station": "34504"},
    {"id": "746", "slug": "kremennaya",               "name": "Кремінна",              "station": "34504"},
    {"id": "161", "slug": "svatovo",                  "name": "Сватове",               "station": "34504"},
    # ── Одеська область ───────────────────────────────────────────────
    {"id": "111", "slug": "odessa",                   "name": "Одеса",                 "station": "33837"},
    {"id": "118", "slug": "izmail",                   "name": "Ізмаїл",                "station": "33837"},
    {"id": "110", "slug": "ilichevsk",                "name": "Чорноморськ",           "station": "33837"},
    {"id": "951", "slug": "kotovsk",                  "name": "Подільськ",             "station": "33837"},
    {"id": "117", "slug": "bolgrad",                  "name": "Болград",               "station": "33837"},
    {"id": "952", "slug": "yujnoe",                   "name": "Южне",                  "station": "33837"},
    {"id": "955", "slug": "balta",                    "name": "Балта",                 "station": "33837"},
    {"id": "958", "slug": "kiliya",                   "name": "Кілія",                 "station": "33837"},
    {"id": "960", "slug": "reni",                     "name": "Рені",                  "station": "33837"},
    {"id": "963", "slug": "zatoka",                   "name": "Затока",                "station": "33837"},
    {"id": "980", "slug": "ovidiopol",                "name": "Овідіополь",            "station": "33837"},
    {"id": "964", "slug": "sergeevka",                "name": "Сергіївка",             "station": "33837"},
    # ── Миколаївська область ──────────────────────────────────────────
    {"id": "112", "slug": "nikolaev",                 "name": "Миколаїв",              "station": "33846"},
    {"id": "103", "slug": "voznesensk",               "name": "Вознесенськ",           "station": "33846"},
    {"id": "104", "slug": "bashtanka",                "name": "Баштанка",              "station": "33846"},
    {"id": "929", "slug": "yuzhnoukrainsk",           "name": "Южноукраїнськ",         "station": "33846"},
    {"id": "113", "slug": "ochakov",                  "name": "Очаків",                "station": "33846"},
    {"id": "931", "slug": "novyy-bug",                "name": "Новий Буг",             "station": "33846"},
    {"id": "930", "slug": "novaya-odessa",            "name": "Нова Одеса",            "station": "33846"},
    # ── Херсонська область ────────────────────────────────────────────
    {"id": "122", "slug": "herson",                   "name": "Херсон",                "station": "33902"},
    {"id": "1170","slug": "kakhovka",                 "name": "Каховка",               "station": "33902"},
    {"id": "124", "slug": "genichesk",                "name": "Генічеськ",             "station": "33902"},
    {"id": "1173","slug": "skadovsk",                 "name": "Скадовськ",             "station": "33902"},
    {"id": "1171","slug": "berislav",                 "name": "Берислав",              "station": "33902"},
    {"id": "1202","slug": "chaplinka",                "name": "Чаплинка",              "station": "33902"},
    {"id": "125", "slug": "askaniya-nova",            "name": "Асканія-Нова",          "station": "33902"},
    # ── Запорізька область ────────────────────────────────────────────
    {"id": "172", "slug": "zaporizhia",               "name": "Запоріжжя",             "station": "34519"},
    {"id": "178", "slug": "melitopol",                "name": "Мелітополь",            "station": "34609"},
    {"id": "181", "slug": "berdyansk",                "name": "Бердянськ",             "station": "34712"},
    {"id": "528", "slug": "energodar",                "name": "Енергодар",             "station": "34519"},
    {"id": "529", "slug": "vasilevka",                "name": "Василівка",             "station": "34519"},
    {"id": "527", "slug": "tokmak",                   "name": "Токмак",                "station": "34519"},
    {"id": "534", "slug": "orehov",                   "name": "Оріхів",                "station": "34519"},
    {"id": "175", "slug": "kirillovka",               "name": "Кирилівка",             "station": "34519"},
    {"id": "173", "slug": "gulyaypole",               "name": "Гуляйполе",             "station": "34519"},
]
