name: "Meteo UA Weather"
description: >-
  Погода з meteo.ua для Home Assistant.
  При першому запуску автоматично встановить інтеграцію Meteo UA Weather
  та карточку прогнозу погоди. 
  /
  Weather from meteo.ua for Home Assistant.
  On first start automatically installs Meteo UA Weather integration and
  forecast card.
version: "3.0.13"
slug: "meteo_ua_weather"
url: "https://github.com/dmdukr/ha-addon-meteo-ua-weather"
arch:
  - amd64
  - aarch64
ports:
  5581/tcp: 5581
ports_description:
  5581/tcp: "HTTP API"
options:
  log_level: "info"
schema:
  log_level: list(debug|info|warning|error)
startup: "application"
boot: "auto"
init: false
map:
  - config:rw
homeassistant_api: true
hassio_api: true
hassio_role: "manager"
